name: 'Docker Publish'

on:
  push:
    tags:
      - '*'

permissions:
  packages: write

jobs:
  publish-beta:
    name: Docker Publish Beta

    runs-on: ubuntu-latest

    if: ${{ contains(github.ref, '-b') }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Prepare
        run: echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: '.'
          file: './Dockerfile'
          platforms: 'linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x'
          push: true
          tags: |
            ttionya/fail2ban:${{ env.TAG }}
