name: 'GitHub Release'

on:
  push:
    tags:
      - '*.*.*-*-*'
      - '!*.*.*-*-b*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            [CHANGELOG](https://github.com/ttionya/fail2ban/blob/master/CHANGELOG.md)
